### ISSUE TITLE
Support Nullable Types on props | Flutter 2.0 and Dart 2.12 upgrade

### ISSUE THREAD

**Issue by Edorin9** [felangel/equatable#111]
**Describe the bug**
The props override property of an equatable doesn't support nullable (eg: String?) values.

**To Reproduce**

1. Upgrade flutter on stable channel (flutter channel stable && flutter upgrade)
2. Upgrade dart sdk version to sdk: ">=2.12.0 <3.0.0"
3. Create an equatable with a nullable property (final String? name)
4. Pass the 'name' property in the equatable props array
```
@override
  List<Object> get props => [name];
```

**Expected behavior**
No IDE errors/build errors should show up

**A possible workaround on my side is to**
Assign a fallback value / ternary, which I would say is not reecommended
```
@override
  List<Object> get props => [name ?? ''];
```

**Additional context**
The element type 'String?' can't be assigned to the list type 'Object'.

**Comment by felangel** [comment]
Hi @Edorin9 👋 
Thanks for opening an issue!

If you want to use nullable props you can just update the `props` override:

```dart
@override
List<Object?> get props => [name];
```

Hope that helps 👍

**Comment by felangel** [comment]
@Edorin9 can this be closed or are you still having trouble with nullable props?

**Comment by Edorin9** [comment]
Thanks for the reply @felangel. We can close it for now. I've actually downgraded flutter and quit upgrading a project, since there are other packages that needs updating as well.

**Comment by JakeHadley** [comment]
@felangel I was having the same issue, with vscode, I added in the nullable operator (?) and I got this error from vscode...
```
('List<Object>? Function()') isn't a valid override of 'Equatable.props' ('List<Object?> Function()').dart(invalid_override)
```
Granted, my code doesn't currently have anything to return, so I just have `List<Object>? get props => null;` which causes this error.

**Comment by felangel** [comment]
@JakeHadley the override should be:

`List<Object?> get props => [];`

Hope that helps 👍

**Comment by JakeHadley** [comment]
Ah yes, that helps a lot. Thanks!

**Comment by luandnguyen** [comment]
@felangel Appreciate the solution. Should this be mentioned in the README?

**Comment by ariefwijaya** [comment]
> @JakeHadley if you don’t have any props the override should be:
> 
> `List<Object> get props => [];`
> 
> If you have nullable props it should be:
> 
> `List<Object?> get props => [propA, propB];`
> 
> Hope that helps 👍

I can't make this work. I've tried `List<Object?>` but I got this `'NotificationNavigateScreen.props' ('List<Object?> Function()') isn't a valid override of 'NotificationState.props' ('List<Object> Function()')`

**Comment by robyhuzwandar** [comment]
> > @JakeHadley if you don’t have any props the override should be:
> > `List<Object> get props => [];`
> > If you have nullable props it should be:
> > `List<Object?> get props => [propA, propB];`
> > Hope that helps 👍
> 
> I can't make this work. I've tried `List<Object?>` but I got this `'NotificationNavigateScreen.props' ('List<Object?> Function()') isn't a valid override of 'NotificationState.props' ('List<Object> Function()')`

Hi @felangel  how about that I got the error too

**Comment by felangel** [comment]
> > > @JakeHadley if you don’t have any props the override should be:
> > > `List<Object> get props => [];`
> > > If you have nullable props it should be:
> > > `List<Object?> get props => [propA, propB];`
> > > Hope that helps 👍
> > 
> > 
> > I can't make this work. I've tried `List<Object?>` but I got this `'NotificationNavigateScreen.props' ('List<Object?> Function()') isn't a valid override of 'NotificationState.props' ('List<Object> Function()')`
> 
> Hi @felangel how about that I got the error too

Can you share a minimal reproduction sample?

**Comment by ariefwijaya** [comment]
Sorry, my bad. I found it. I need to use `List<Object?>` in my abstract class when extending Equatable. Just because my abstract is not nullable, it will force the child to be non-nullable too.

**Comment by Ashrafe** [comment]
> Sorry, my bad. I found it. I need to use `List<Object?>` in my abstract class when extending Equatable. Just because my abstract is not nullable, it will force the child to be non-nullable too.

yea that's it  ty

**Comment by AnnaPS** [comment]
> @JakeHadley if you don’t have any props the override should be:
> 
> `List<Object> get props => [];`
> 
> If you have nullable props it should be:
> 
> `List<Object?> get props => [propA, propB];`
> 
> Hope that helps 👍

Thank you Felix, I was looking for this solution :)
