### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by DarkHeros09** [felangel/equatable#113]
Hello Felix
First of all I'd like to thank you for your efforts for creating such awesome packages.🙏

**Describe the bug**
Before upgrading to null safety, everything was working correctly.
normally i create an Entity class that extends equatable, then when i create a Model class that extends the entity"following clean architecture", and when i run the tests everything is OK... that's before upgrading to null safety.

Now when i run the tests i get this error `"Null check operator used on a null value"`.

**To Reproduce**
install the following:

```
dependencies:
  equatable: ^2.0.0
  freezed_annotation: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  freezed: ^0.14.1+1
  json_serializable: ^4.1.0
```

** The Files **

product.dart
```
class Product extends Equatable {
  final int? id;
  final String? brand;
  final String? name;
const Product({
    this.id,
    this.brand,
    this.name,
});

@override
  List<Object> get props {
    return [
      id!,
      brand!,
      name!,
];}}
```

product_model.dart
```
@JsonSerializable()
class ProductModel extends Product {
 final int? id;
 final String? brand;
 final String? name;
const ProductModel({
    this.id,
    this.brand,
    this.name,
}):super( 
id: id,
brand: brand,
name: name,);

  factory ProductModel.fromJson(Map<String, dynamic> json) =>
      _$ProductModelFromJson(json);

  Map<String, dynamic> toJson() => _$ProductModelToJson(this);
```

product_model_test.dart
```
void main() {
  const tProductModel = <ProductModel>[
    ProductModel(
      id: 1048,
      brand: "colourpop",
      ],
    )
  ];
  setUp(() {});

  test('should be a subclass of product entity', () async {
    //assert
    expect(tProductModel, isA<List<Product>>());
  });

  group('fromJson', () {
    test('should return a valid product data model from json', () async {
      //arrange
      final List<dynamic> jsonMap =
          jsonDecode(fixture('product.json')) as List<dynamic>;
      //act
      final List<ProductModel> result = jsonMap
          .map((dynamic i) => ProductModel.fromJson(i as Map<String, dynamic>))
          .toList();

      //assert
      expect(result, tProductModel);
    });
  });
```

product.json
```
[
  {
  "id": 1048,
  "brand": "colourpop"
}
]
```

fixture_reader.dart
```
String fixture(String name) => File('test/fixtures/$name').readAsStringSync();
```

**Expected behavior**
The test should pass as before, unless I'm missing something.

**Screenshots**
![equatable_error](https://user-images.githubusercontent.com/39935182/112751901-9fafcc00-8fd0-11eb-9426-5049b8926f55.JPG)

**Version**
Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "windows_x64"

**Comment by felangel** [comment]
Hi @DarkHeros09 👋 
Thanks for opening an issue and for the positive feedback! I believe this is a duplicate of https://github.com/felangel/equatable/issues/111

Your props override should look like:

```dart
  @override
  List<Object?> get props {
    return [
      id,
      brand,
      name,
    ];
```

Hope that helps! 👍

**Comment by DarkHeros09** [comment]
yes you are correct, the test is passed now. 
forgive me, i should've checked the closed issues.

Thank you very much for the clarification, btw great job on mocktail its a life saver.
