### ISSUE TITLE
Should EquatableMixin.== have Object instead of Object? as an argument?

### ISSUE THREAD

**Issue by tuanvugoodmoney** [felangel/equatable#115]
**Describe the bug**
Ran across Artemis generating classes with EquatableMixin, but am unable to mock those classes using mocktail, because EquatableMixin's [signature](https://github.com/felangel/equatable/blob/master/lib/src/equatable_mixin.dart#L19) for `==` is `bool operator ==(Object? other)` while mocktail's is `bool operator ==(Object other)` 

**To Reproduce**

Try to override a class with EquatableMixin.

**Expected behavior**
EquatableMixin.== to be the same as Equatable.==.

**Screenshots**
```
'Mock.==' ('bool Function(Object)') isn't a valid concrete implementation of 'EquatableMixin.==' ('bool Function(Object?)').
```

**Version**
Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "macos_x64"

**Additional context**
N/A

**Comment by mpkander** [comment]
@felangel #108 was too breaking. Is there any chance to roll back this change?

it's unable to mock classes that uses EquatableMixin

**Comment by felangel** [comment]
If we rollback those changes the mixin will no longer work with classes that use `dynamic` in their `==` override. But yes, I think `Object` is the correct implementation so I think it makes sense 👍

**Comment by SEGVeenstra** [comment]
> @felangel #108 was too breaking. Is there any chance to roll back this change?
> 
> it's unable to mock classes that uses EquatableMixin

How are you currently working around this? We have so much breaking mocks right now.
Some of us started to rename the files, and remove them from `@GenerateMocks` so we can manually fix them, but this is a lot of manual labor.

**Comment by felangel** [comment]
> > @felangel #108 was too breaking. Is there any chance to roll back this change?
> > it's unable to mock classes that uses EquatableMixin
> 
> How are you currently working around this? We have so much breaking mocks right now.
> Some of us started to rename the files, and remove them from `@GenerateMocks` so we can manually fix them, but this is a lot of manual labor.

Regarding mocking I use [mocktail](https://pub.dev/packages/mocktail) which doesn’t appear to be affected by this.

**Comment by SEGVeenstra** [comment]
> Regarding mocking I use mocktail which doesn’t appear to be affected by this.

It might be an option for us, because we also use bloc_test. But it will affect most of our non-bloc unit tests.
On top of that, our team tries to avoid 0.X.X versions as much as possible.

As this is considered a bug, is there any ETA on when this will be fixed/released?

**Comment by felangel** [comment]
@SEGVeenstra yeah I'll get a fix for this by end of day today, sorry for the inconvenience!

**Comment by SEGVeenstra** [comment]
> @SEGVeenstra yeah I'll get a fix for this by end of day today, sorry for the inconvenience!

Awesome! Thank you for your hard work, your efforts are greatly appreciated!
