### ISSUE TITLE
Strange behavior when comparing objects with lists

### ISSUE THREAD

**Issue by samuellow** [felangel/equatable#126]
class AccountSelectionState extends LoginState {
      final List<String> accounts;
    
      final List<bool> selected;
    
      AccountSelectionState(this.accounts, this.selected);
    
      @override
      List<Object> get props => List.from(accounts)..addAll(selected);
    }

The equality check always returns true for the above state with two list attributes, even when provided with different list values.

The workaround was to capture a snapshot of the attributes.

    class AccountSelectionState extends LoginState {
      final List<String> accounts;
    
      final List<bool> selected;

      final List<Object> values;
    
      AccountSelectionState(this.accounts, this.selected) :
        values = List.from(accounts)..addAll(selected);    

      @override
      List<Object> get props => values;
    }

Is this the expected behavior?

**Comment by SEGVeenstra** [comment]
I'm actually curious as well.
I landed here because I was looking for the (best) way to `List`/`Map` fields to the `props`. I didn't even think about just putting all elements in there.

**Comment by SEGVeenstra** [comment]
> ```
> class AccountSelectionState extends LoginState {
>   final List<String> accounts;
> 
>   final List<bool> selected;
> 
>   AccountSelectionState(this.accounts, this.selected);
> 
>   @override
>   List<Object> get props => List.from(accounts)..addAll(selected);
> }
> ```
> 
> The equality check always returns true for the above state with two list attributes, even when provided with different list values.
> 
> The workaround was to capture a snapshot of the attributes.
> 
> ```
> class AccountSelectionState extends LoginState {
>   final List<String> accounts;
> 
>   final List<bool> selected;
> 
>   final List<Object> values;
> 
>   AccountSelectionState(this.accounts, this.selected) :
>     values = List.from(accounts)..addAll(selected);    
> 
>   @override
>   List<Object> get props => values;
> }
> ```

Would using the spread operator work as well?
```dart
@override
List<Object> get props =>List.of([...accounts,...selected]);
```

**Comment by SEGVeenstra** [comment]
Just ran into this again.
Using:
```dart
@override
List<Object> get props => List.of([...accounts,...selected]);
```
cannot be trusted because the order changes the outcome.

I've solved this by using the following on each `List`-property that I want to be considered equal, even when the items are in a different order:
```dart
list.sortedBy<num>((element) => element.hashCode).toList();
```

So in this example it would be:
```dart
@override
List<Object> get props =>List.of([
  ...accounts.sortedBy<num>((element) => element.hashCode).toList(),
  ...selected.sortedBy<num>((element) => element.hashCode).toList(),
]);
```

**Comment by pinkasey** [comment]
Am I missing something?
I would assume the right way to implement `props` for this class would be
```
class AccountSelectionState extends LoginState {
  final List<String> accounts;

  final List<bool> selected;

  AccountSelectionState(this.accounts, this.selected);

  @override
  List<Object> get props => [ accounts, selected ];
}
```

**Comment by SEGVeenstra** [comment]
> Am I missing something?
> I would assume the right way to implement `props` for this class would be
> 
> ```
> class AccountSelectionState extends LoginState {
>   final List<String> accounts;
> 
>   final List<bool> selected;
> 
>   AccountSelectionState(this.accounts, this.selected);
> 
>   @override
>   List<Object> get props => [ accounts, selected ];
> }
> ```

I think you are correct. I personally got sidetracked because I wanted the lists to be equal even if the items were in different orders.

I simply solved that by using a `Set` instead of a `List`.

**Comment by ariefwijaya** [comment]
Set also doesn't work for me
