### ISSUE TITLE
Add option to exclude properties for equal check

### ISSUE THREAD

**Issue by JulianBissekkou** [felangel/equatable#127]
**Is your feature request related to a problem? Please describe.**
I am doing an equal check on two instances and I want to have a nice syntax for excluding properties.

**Describe the solution you'd like**
Since this might be a niche problem my suggestion would be to provide a static helper function that does this.
I would not add this to the `EqualtableMixin`.

Here is a small example:
```dart
  static bool isEqualExcluding<T extends EquatableMixin>(
    T lhs,
    T rhs,
    Object Function(T)? excludeProperty,
  ) {
    if (excludeProperty == null) return lhs == rhs;

    final lhsProperties = lhs.props
        .where((property) => property == excludeProperty(lhs))
        .toList();
    final rhsProperties = rhs.props
        .where((property) => property == excludeProperty(rhs))
        .toList();

    return equatable_utils.equals(lhsProperties, rhsProperties);
  }
```

(The current implementation will not work if a class has two properties with the same value)

**Comment by alvinvin00** [comment]
just don't include that excluded properties on props list, i don't know what's the use case for this tbh

**Comment by JulianBissekkou** [comment]
Excluding a property just for a specific operation. Excluding the property in the props list will affect all equal checks.

**Comment by Ascenio** [comment]
I don't think that's possible. In your app you can compare two objects of the same class using different combination of fields, it would be hard to implement something so generic without some trickery like code generation (which some don't like).

However, you can always create helper methods, like this:
```dart
import 'package:equatable/equatable.dart';

class Person extends Equatable {
  final int age;
  final String name;

  Person(this.name, this.age);

  bool equalsByAge(Person other) {
    return age == other.age;
  }

  bool equalsByName(Person other) {
    return name == other.name;
  }

  @override
  List<Object> get props => [age, name];
}

void main() {
  final someBob = Person('Bob', 42);
  final anotherBob = Person('Bob', 42);
  final alice = Person('Alice', 69);

  // By all fields
  print(someBob == anotherBob); // true

  // By specific fields
  print(someBob.equalsByAge(anotherBob)); // true
  print(someBob.equalsByName(anotherBob)); // true
  print(someBob.equalsByName(alice)); // false
  print(someBob.equalsByAge(alice)); // false
}
```
