### ISSUE TITLE
Use Dart 2.14's new hashing functions

### ISSUE THREAD

**Issue by hacker1024** [felangel/equatable#129]
Dart 2.14 adds new hashing methods like [`Object.hash`](https://api.dart.dev/stable/2.14.4/dart-core/Object/hash.html) (uses optional arguments for up to 20 objects) and [`Object.hashAll`](https://api.dart.dev/stable/2.14.4/dart-core/Object/hashAll.html) (uses a list for a large or variable number of objects).

The reasoning behind this addition to the language can be found at https://github.com/dart-lang/sdk/issues/11617.
Also see https://dart-review.googlesource.com/c/sdk/+/73360.

Using the built-in hashing functions would allow this package to have a smaller footprint and fit in with everything else if the Dart maintainers ever decide to change or optimise the hashing algorithm.

**Comment by hacker1024** [comment]
I've just had a go at implementing this, but it's more complicated than I initially expected due to the recursive collection hashing functionality.

I have a question: Why not use `_equality`'s `hash` method in `mapPropsToHashCode`? It seems to do the same thing as the existing implementation, although I'm not sure if it uses the same algorithm.

**Comment by felangel** [comment]
I'm closing this for now as `Object.hashAll` isn't functionally equivalent to the current implementation.
