### ISSUE TITLE
Should we always call super([...])?

### ISSUE THREAD

**Issue by pedromassango** [felangel/equatable#13]
I just saw the code sample provided at README file:

```Dart
import 'package:equatable/equatable.dart';

class Person extends Equatable {
  final String name;

  Person(this.name) : super([name]);
}
```

I want to know if we should always call the super function providing all my properties or just extends with Equatable and we are ready to go?!

**Comment by felangel** [comment]
Hey @pedromassango 👋 

Yes, you should always pass the properties to the super class when using Equatable. Great question! 👍

**Comment by pedromassango** [comment]
Thank you.
