### ISSUE TITLE
Comparing Derived Classes Fails When Shared Properties Are The Same

### ISSUE THREAD

**Issue by SupposedlySam** [felangel/equatable#132]
**Describe the bug**
When passing in a derived class (subclass) and doing an equality comparison, the comparison fails.

**To Reproduce**
```dart
import 'package:equatable/equatable.dart';

void main() {
  const String sameValue = 'shouldBeEqual';

  final c = C(A(sameValue), B(sameValue, 'someOtherValue'));

  print(c.compare); // false
}

class A extends Equatable {
  const A(this.sameValue);

  final String sameValue;

  @override
  List<Object> get props => [sameValue];
}

class B extends A {
  const B(String sameValue, this.differentValue) : super(sameValue);

  final String differentValue;

  @override
  List<Object> get props => [differentValue, ...super.props];
}

class C {
  const C(this.firstClass, this.secondClass);

  final A firstClass;
  final A secondClass;

  bool get compare => firstClass == secondClass;
}

```

**Expected behavior**
Since class `C` is requiring two classes of type `A`, I would expect for `c.compare` to return `true` since `a.sameValue` and `b.sameValue` are equal between the two instances.

**Version**
Equatable: ^2.0.3
Dart SDK version: 2.15.0 (stable) (Fri Dec 3 14:23:23 2021 +0100) on "macos_x64"

**Comment by felangel** [comment]
Hey @SupposedlySam 👋 
Thanks for opening an issue!

I believe this is a duplicate of #131. I left a comment with my thoughts but lmk what you think 👍

**Comment by SupposedlySam** [comment]
I've worked with Morgan on a proposal. Linking the draft PR.

**Comment by mrgnhnt96** [comment]
Here is a possible solution for this #133

**Comment by SupposedlySam** [comment]
Closing as dup of #131. Conversation continued there.
