### ISSUE TITLE
Equatable doesn't checks for Equality for variables in parent class

### ISSUE THREAD

**Issue by LeeBoonKong** [felangel/equatable#143]
I have a state bloc

```
abstract class BaseState extends Equatable{
    List<MyObject> listA;
    List<MyObject> listB;
    BaseState(this.listA, this.listB);

    @override
    List<Object> get props => [listA, listB]
}

class StateA extends BaseState{
    BaseState(List<MyObject> newListA, List<MyObject> newListB): super(List.of(newListA), List.of(newListA));
}
```

As the example above, while receiving StateA from BlocBuilder using flutter_bloc, Equatable is not able to detect the difference in StateA hence the UI is not updated.

Is my implementation and the way of using Equatable correct in this regard?

**Comment by MdSaLaMa** [comment]
the same problem 
`print('object' == 'object'); //true    
 print(['object'] == ['object']); //false
 print({1: 'object'} == {1: 'object'});//false`

**Comment by RobertPietraru** [comment]
An year late, but does MyObject extend Equatable? If it doesn't it won't work

**Comment by felangel** [comment]
Closing this issue for now since it's quite old. Feel free to comment if you're still having trouble and I'm happy to take a closer look, thanks!
