### ISSUE TITLE
Provide lint for forgotten fields in props

### ISSUE THREAD

**Issue by petrnymsa** [felangel/equatable#158]
It would be nice to have some kind of lint, which will warn about the forgotten field in `props`. Most of the time, any public field of the class has to be included in `props`. 

We have some automation with help of extensions in IDE for generating props but it cant prevent bugs by forgetting to update the props field.

**Comment by Yczar** [comment]
@felangel is this a feasible feature? I want to play around with this.

**Comment by felangel** [comment]
Thanks so much @incendial 💯
