### ISSUE TITLE
`Equatable` is redundant with `EquatableMixin`

### ISSUE THREAD

**Issue by shilangyu** [felangel/equatable#160]
**Is your feature request related to a problem? Please describe.**

When choosing which one to use (`Equatable` or `EquatableMixin`) there is no benefit of choosing `Equatable` (or I am failing to see one) over the mixin version. This duplicates the API for no clear reason to me.

**Describe the solution you'd like**

Removing the non-mixin version. This simplifies this package, docs, and usage.

**Additional context**

During code reviews I often have to tell people to use the mixin version instead, since it is more extensible (for example will allow in the future to extend some other class).

If I am missing some advantage that the class version has, please let me know what that is and feel free to close this issue.

**Comment by utamori** [comment]
I think this can be solved by making Equatable an Dart3 `abstract mixin class`.
EquatableMixin should be deprecated and removed later.

**Comment by felangel** [comment]
Closing this since it will be resolved by #175

**Comment by ricardodalarme** [comment]
Now that Macros has been discontinued, it would be a good idea to reopen this issue

**Comment by felangel** [comment]
This has been published in the v2.1.0-dev.0 pre-release. Please give it a try and let me know if you encounter any issues, thanks! 🙏
