### ISSUE TITLE
Upgrade sdk to include Dart 3

### ISSUE THREAD

**Issue by soeren-schmaljohann-2denker** [felangel/equatable#162]
**Is your feature request related to a problem? Please describe.**
The current version only supports Dart 2.

**Describe the solution you'd like**
Upgrade the package to include the Dart 3 SDK.

**Comment by devpawann** [comment]
#145  Supports it

**Comment by felangel** [comment]
Hi @soeren-schmaljohann-2denker 👋 
The latest version is compatible with Dart 3 as well. If you're running into a specific issue please feel free to provide a minimal reproduction sample and I'm happy to take a closer look. Closing for now, thanks!

**Comment by soeren-schmaljohann-2denker** [comment]
Hi, thanks for coming back to me, the current version works fine for me, thanks for the update!
