### ISSUE TITLE
`Foo(1) == Foo(1.0)` is false

### ISSUE THREAD

**Issue by Mike278** [felangel/equatable#167]
```dart
class Foo with EquatableMixin {
  final num bar;
  Foo(this.bar);

  @override
  List<Object?> get props => [bar];
}

int anInt = 1;
double aDouble = 1.0;
print(anInt == aDouble); // true
print(Foo(anInt) == Foo(aDouble)); // false
```

I understand why comparing `runtimeType`s is useful in general, but I wonder if there should be a special case for `num` - especially considering Dart's support for assigning integer literals to doubles.

**Comment by wednesdei** [comment]
Making an exception for num could lead to unexpected behavior for users who rely on strict type equality. Can you override the equality check in your own classes to suit your needs?

**Comment by felangel** [comment]
Agreed with @wednesdei closing for now as this is working as expected.

**Comment by Mike278** [comment]
[Guess you changed your mind?](https://github.com/felangel/equatable/pull/189/changes) 😅 Just got around to updating an old project and this broke a bunch of tests
