### ISSUE TITLE
The class has the collection variable is not the "List" object.

### ISSUE THREAD

**Issue by phamnhuvu-dev** [felangel/equatable#17]
**Describe the bug**
If the class has the collection variable is not the "List" object. Comparing is always return true.

**To Reproduce**
```
class E extends Equatable {
  final Map<String, int> map;

  E(this.map);
}

E e1 = E({"A": 1});
E e2 = E({"B": 2});
assert(e1 == e2); // return true
```

**Expected behavior**
`assert(e1 != e2) //return true`

**Problem**
https://github.com/felangel/equatable/blob/master/lib/src/equatable_utils.dart#L18-L24

**Solution**
Compare between 2 collections(List, Map, Set, v.v…) have to use Equality object(ListEquality, MapEquality, SetEquality, v.v…) in package:collection/collection.dart.
Don’t use “==” operator.

```
MapEquality mapEquality = MapEquality();
Map map1 = {"A": 1};
Map map2 = {"A": 1};
Map map3 = {"B": 2};
assert(mapEquality.equals(map1, map2)); //map1 == map2
assert(!mapEquality.equals(map2, map3)); //map2 != map3
```

**Comment by felangel** [comment]
@phamnhuvu-dev in your example I noticed you aren't passing the properties to the Equatable superclass.

```dart
class E extends Equatable {
  final Map<String, int> map;

  E(this.map) : super([map]); // missing call to super
}

E e1 = E({"A": 1});
E e2 = E({"B": 2});
assert(e1 == e2); // return true
```
