### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by freshtechtips** [felangel/equatable#171]
It has been a while (15 months) since the package got published, I think it's a good idea to publish a new version `2.0.6` even though not much has changed

but just so the developers who are using the package know that the package is still maintained and supported

**Comment by felangel** [comment]
That seems unnecessary imo. If a package is stable there is no reason to publish new versions with no changes. Closing this for now since I don’t think there’s any benefit in revving the version with no changes.

**Comment by freshtechtips** [comment]
> That seems unnecessary imo. If a package is stable there is no reason to publish new versions with no changes. Closing this for now since I don’t think there’s any benefit in revving the version with no changes.

It depends on your perspective.
