### ISSUE TITLE
Question about syntax: spread operator for subclasses

### ISSUE THREAD

**Issue by lukas-pierce** [felangel/equatable#179]
Not a bug and not a feature request

Can I use spread operator for equatable subclasses

```dart
import 'package:equatable/equatable.dart';

// parent
class Person extends Equatable {
  const Person(this.name);

  final String name;

  @override
  List<Object> get props => [name];
}

// subclass
class Employee extends Person {
  const Employee(
    super.name, {
    required this.salary,
  });

  final double salary;

  @override
  List<Object> get props => [
    ...super.props,
    salary, // extended class adds new field: salary
  ];
}
```

In your documentation you use this construction:

```
  @override
  List<Object> get props => super.props..addAll([century]);
```

But I want to make sure that my approach is justified in terms of performance and equivalence. I couldn't think of anything better than asking the author

**Comment by felangel** [comment]
Hi @lukas-pierce 👋 
Thanks for opening an issue!

Yup, using the spread operator like that should be totally fine 👍

**Comment by lukas-pierce** [comment]
@felangel Thanks for the answer
