### ISSUE TITLE
README suggests mutating superclass props

### ISSUE THREAD

**Issue by munificent** [felangel/equatable#183]
In the README, the example of inheritance has:

```dart
  List<Object> get props => super.props..addAll([century]);
```

If `props` from the superclass always returns a brand new list, then this code is probably fine. But if the superclass stores a list and returns the same list each time, then this will append `century` to that list over and over again each time `props` is called. That's probably not what the user wants. :)

I think a more reliable pattern is:

```dart
  List<Object> get props => [...super.props, century];
```

**Comment by felangel** [comment]
Good catch! Thanks so much @munificent. Feel free to open a PR otherwise I should be able to fix it later today. 💙
