### ISSUE TITLE
breaking change: `equals` removed in v2.0.6

### ISSUE THREAD

**Issue by LukasMirbt** [felangel/equatable#187]
**Describe the bug**
The public `equals` function was removed from `equatable_utils.dart` in v2.0.6 causing dependent code to break.

**Additional context**
In my case, I use the [dart-dio OpenAPI generator](https://openapi-generator.tech/docs/generators/dart-dio/) with `equalityCheckMethod: equatable` which broke in v2.0.6.

**Comment by felangel** [comment]
Sorry about that! I’ll get a fix out shortly — I was under the impression that the utilities were not publicly exported.

**Comment by felangel** [comment]
@LukasMirbt I just took a look and it doesn't look like `equals` or any of the `equatable_utils` were publicly exported in v2.0.5. They open api generator was directly importing a private method straight from the src directory which is never safe :(

**Comment by LukasMirbt** [comment]
Hm, yea you're right. It imports `'package:equatable/src/equatable_utils.dart';` which one could argue makes it not a breaking change.

Is it still worth adding it back considering how widely used the package is and that it breaks some use cases (even if the file is inappropriately imported)?

**Comment by felangel** [comment]
Even though it's technically not a breaking change I re-introduced `equals` in #190

**Comment by felangel** [comment]
This should be fixed in v2.0.7 🎉
