### ISSUE TITLE
How do you change the value of a state.posts[index].fieldname 

### ISSUE THREAD

**Issue by raindy29** [felangel/equatable#21]
I can successfully execute,but But can't synchronize key/value
state.posts[0].props[8] = 'abcd';

**Comment by felangel** [comment]
Hi @raindy29 👋 
Thanks for opening an issue!

All classes that extends Equatable are immutable so you cannot change their props.
Why are you trying to modify the props?

**Comment by raindy29** [comment]
I use bloc and equatable to generate a listview widget, I want to dynamically change the item value, but I can't find any  method.

**Comment by felangel** [comment]
You can’t change the item value because bloc state is immutable. You have to yield a new state every time instead of trying to modify the existing state. Please refer to the [bloc docs](https://felangel.github.io/bloc/#/coreconcepts) for more details.

**Comment by raindy29** [comment]
Thank you for your reply.
I have tried removeat/add to complete the row change, but there is no easy way to update the key/value

**Comment by felangel** [comment]
Can you please provide a link to your application? It will be much easier to help if I can see your implementation.

**Comment by raindy29** [comment]
Thanks for your tips, problem has solved

bloc code
        final List<orde> newposts =
        List<orde>.from(listState.posts).map((orde item) {
          return item.id == event.id ? item.copyWith(orde_type: event.orde_type) : item;
        }).toList();

model code
  orde copyWith({
    String orde_type,
  }) {
    return orde(
      orde_type: orde_type ?? this.orde_type,
.....
