### ISSUE TITLE
Allow const constructors

### ISSUE THREAD

**Issue by AnEnigmaticBug** [felangel/equatable#24]
I would like to use Equatable for my model classes. But if I use it, I can't make them `const`. Since I use them in my UI widgets, I'll be forced to make them non-`const` too. Which is something I would like to avoid.

If you can somehow solve this issue, IMHO it would be a useful addition to this wonderful package.

This was already raised in #2 but that issue was closed by its author.

**Comment by felangel** [comment]
Hi @AnEnigmaticBug 👋 
Thanks for opening an issue!

I'll try to spend some time this weekend investigating this 👍

**Comment by felangel** [comment]
Closing this as I don't believe it's possible since props must be injected and cannot be const.
