### ISSUE TITLE
Add a const constructor and make props @protected.

### ISSUE THREAD

**Issue by jifalops** [felangel/equatable#31]
**Is your feature request related to a problem? Please describe.**
I would like to use Equatable with my data classes that have const constructors.

**Describe the solution you'd like**
Add a const constructor option to `Equatable` such as

```dart
const Equatable.const([this.props = const []]);
```
I started making a PR for this but it also seems like the Equatable class should mixin EquatableMixin (after accepting #30) to eliminate duplicated code. I'm not really sure how to go about all this but it seems like it should be easy enough.

**Comment by jifalops** [comment]
After messing around with this for a bit I kind of hit a wall. See https://github.com/dart-lang/language/issues/544

**Comment by felangel** [comment]
Hi @jifalops 👋 
Thanks for opening an issue!

I also tried supporting this request in https://github.com/felangel/equatable/issues/24 but as you mentioned I don't think it is possible.

Closing for now but I'm open to ideas/suggestions

**Comment by rrousselGit** [comment]
This is possible if we override the `props` getter:

```dart
class ConstTest extends Equatable {
  const ConstTest(this.a);

  final int a;

  @override
  List<Object> get props => [a];
}
```
