### ISSUE TITLE
Version 6 has a bug with passing to super.

### ISSUE THREAD

**Issue by jrmarkham** [felangel/equatable#36]
**Describe the bug**
I have a project using your blocs and I was using equatable 6.1 on events and states. I had an event that would fire twice and then nada. I downgrade to 5.1 and it worked perfectly.

I have a github of the project if you’d like to see the updates. It is tiny project w/ only one bloc.

By the way I love your plugins— you did an excellent job.

Here is the project:

https://github.com/jrmarkham/7dieroller

Here are the updates so you don't have to dig:
`
========== problems w/ 6.1 =========================
import 'package:equatable/equatable.dart';

abstract class FirebaseState extends Equatable {
const FirebaseState([List props = const []]);
@override
List get props => [props];
}

class FirebaseStateInit extends FirebaseState {}
class FirebaseStateLoading extends FirebaseState {}
class FirebaseStateInitResponse extends FirebaseState {
final Stream stream;
FirebaseStateInitResponse(this.stream);

@override
List get props => [stream];
}
class FirebaseStateLoaded extends FirebaseState {

}

===== works w/ 5.1 ============
import 'package:equatable/equatable.dart';

abstract class FirebaseEvent extends Equatable {
FirebaseEvent([List props = const []]):super(props);
}

class FirebaseEventRollDie extends FirebaseEvent {}

========================

import 'package:equatable/equatable.dart';

abstract class FirebaseState extends Equatable {
FirebaseState([List props = const []]):super(props);
}

class FirebaseStateInit extends FirebaseState {}
class FirebaseStateLoading extends FirebaseState {}
class FirebaseStateInitResponse extends FirebaseState {
final Stream stream;
FirebaseStateInitResponse(this.stream):super([stream]);
}
class FirebaseStateLoaded extends FirebaseState {

}`

Thanks— John

**Comment by jrmarkham** [comment]
Here are the updates so you don't have to dig: 
`====================================


 import 'package:equatable/equatable.dart';

 abstract class FirebaseState extends Equatable {
   const FirebaseState([List props = const <dynamic>[]]);
   @override
   List<Object> get props => [props];
 }

 class FirebaseStateInit extends FirebaseState {}
 class FirebaseStateLoading extends FirebaseState {}
 class FirebaseStateInitResponse extends FirebaseState {
   final Stream stream;
   FirebaseStateInitResponse(this.stream);

   @override
   List<Object> get props => [stream];
 }
 class FirebaseStateLoaded extends FirebaseState {

 } 





===== works w/ 5.1 ============
import 'package:equatable/equatable.dart';

abstract class FirebaseEvent extends Equatable {
  FirebaseEvent([List props = const []]):super(props);
}

class FirebaseEventInit extends FirebaseEvent {}
class FirebaseEventSetInitVars extends FirebaseEvent {
  final bool lock;
  final List<dynamic> pool;
  final int roll;
  FirebaseEventSetInitVars(this.lock, this.pool, this.roll):super([lock,pool,roll]);
}
class FirebaseEventRollDie extends FirebaseEvent {}


========================



import 'package:equatable/equatable.dart';

abstract class FirebaseState extends Equatable {
  FirebaseState([List props = const []]):super(props);
 }

class FirebaseStateInit extends FirebaseState {}
class FirebaseStateLoading extends FirebaseState {}
class FirebaseStateInitResponse extends FirebaseState {
  final Stream stream;
  FirebaseStateInitResponse(this.stream):super([stream]);
}
class FirebaseStateLoaded extends FirebaseState {

}`

**Comment by felangel** [comment]
Hi @jrmarkham 👋 
Thanks for opening an issue!

I've created a [pull request](https://github.com/jrmarkham/7dieroller/pull/1) to update to Equatable v0.6.0. Can you please take a look and let me know if that helps? Thanks! 👍

**Comment by jrmarkham** [comment]
Looks good-- but I am rejecting your merge. Because this is a test project for prospective employer so I don't want her to think there was any funny business. She's former dev so she'd probably understand but I'd rather not take the risk. Thanks for the help and I'll run your updates locally on my build.

**Comment by felangel** [comment]
@jrmarkham no problem and sounds good 👍

**Comment by jrmarkham** [comment]
Ok -- I test on 6.0 and 6.1 and  both work.  (thumb) 

I'd just emphasize in your docs the you need this on event/states without props; that I think was the original issue I believe. Again, thanks for the BLoC and equatable packages they areis really helpful. 

`  @override
  List<Object> get props => [];`

**Comment by felangel** [comment]
@jrmarkham thanks for confirming 👍 

Yup, I'll improve the docs. Thanks for the feedback!
