### ISSUE TITLE
False positive equality with Lists

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [felangel/equatable#41]
**Describe the bug**
I have 2 states that are showing up equal when lists are involved.
```dart
@immutable
class TrackerState extends Equatable {
  final WordIndex currentMatch;
  final List<String> resultsHistory;
  final bool isAvailable;
  final bool isListening;
  final List<String> source;

  @override
  String toString() {
    return 'TrackerState{currentIndex: $currentMatch, '
        'resultsHistory: $resultsHistory, isAvailable: $isAvailable, '
        'isListening: $isListening}';
  }

  TrackerState({
    @required this.currentMatch,
    @required this.resultsHistory,
    @required this.isAvailable,
    @required this.isListening,
    @required this.source,
  });

  TrackerState copyWith({
    WordIndex currentMatch,
    List<String> resultsHistory,
    bool isAvailable,
    bool isListening,
    List<String> source,
  }) {
    return TrackerState(
      currentMatch: currentMatch ?? this.currentMatch,
      resultsHistory: resultsHistory ?? this.resultsHistory,
      isAvailable: isAvailable ?? this.isAvailable,
      isListening: isListening ?? this.isListening,
      source: source ?? this.source,
    );
  }

  @override
  List<Object> get props =>
      [currentMatch, resultsHistory, isAvailable, isListening];
}
```
<img width="722" alt="Screen Shot 2019-11-18 at 2 27 18 PM" src="https://user-images.githubusercontent.com/23037821/69099598-ff2abe80-0a0f-11ea-8f7e-0a60c69c0bf7.png">

<img width="780" alt="Screen Shot 2019-11-18 at 2 27 40 PM" src="https://user-images.githubusercontent.com/23037821/69099603-ff2abe80-0a0f-11ea-8dd6-204cc4febfa6.png">
<img width="743" alt="Screen Shot 2019-11-18 at 2 27 54 PM" src="https://user-images.githubusercontent.com/23037821/69099600-ff2abe80-0a0f-11ea-9a2e-3a057a55b00b.png">

**Expected behavior**
Classes with Lists of different lengths or contents should be considered equal

**Screenshots**

**Version**
Dart VM version: 2.7.0 (Thu Nov 14 02:10:15 2019 +0000) on "macos_x64"

**Additional context**

**Comment by felangel** [comment]
Hi @ThinkDigitalSoftware 👋 
Thanks for opening an issue!

I think this is working as expected but because you omitted the `source` property from your `props` it isn't be considered when evaluating the equality of the two instances.

```dart
@override
  List<Object> get props =>
      [currentMatch, resultsHistory, isAvailable, isListening, source]; // add source
```

Can you let me know if that helps? Thanks!

**Comment by ThinkDigitalSoftware** [comment]
Oh (-_-). Oops. Well then. I'll just close this one then :P Thanks!

**Comment by ThinkDigitalSoftware** [comment]
I added that prop after I created the class and forgot to update the getter
