### ISSUE TITLE
Would you be able to explain this weird equatable behaviour?

### ISSUE THREAD

**Issue by mrdavidrees** [felangel/equatable#55]
**Describe the bug**
Equatable is returning false when it should return true

**To Reproduce**
Using equatable 1.0.3
I created the following class
```
class ProjectTreeType implements Equatable {
  final int projectId;
  final int treeTypeId;

  ProjectTreeType(this.projectId, this.treeTypeId);

  @override
  List<Object> get props => [projectId, treeTypeId];
}
```
And ran the following check
```
ProjectTreeType(1, 1) == ProjectTreeType(1, 1)
//return false
```

I wanted to debug in and see which condition was returning false so i imported the equals function and overrode the operator, I was extremely surprised to see that the equals operator returned true
```
import 'package:equatable/src/equatable_utils.dart';

class ProjectTreeType implements Equatable {
  final int projectId;
  final int treeTypeId;

  ProjectTreeType(this.projectId, this.treeTypeId);

  @override
  bool operator ==(Object other) =>
      identical(this, other)
      || other is Equatable 
      && runtimeType == other.runtimeType 
      && equals(props, other.props);

  @override
  List<Object> get props => [projectId, treeTypeId];
}
```
This time it will return true
```
ProjectTreeType(1, 1) == ProjectTreeType(1, 1)
//return true
```

**Additional context**
Am I going mad?

**Comment by felangel** [comment]
Hi @mrdavidrees 👋
Thanks for opening an issue!

I believe the problem is your class is implementing Equatable when it should be extending Equatable. Let me know if that helps 👍

**Comment by mrdavidrees** [comment]
Oh wow. You're totally right. 
Would have never expected to subclass Equatable since, in other programming languages it's always an interface or protocol.

Thanks so much for your help.
