### ISSUE TITLE
Please add copy method with the same logic as stringify, i.e. copy props only.

### ISSUE THREAD

**Issue by slavap** [felangel/equatable#59]

**Comment by felangel** [comment]
Hi @slavap 👋 
Thanks for opening an issue!

Can you please provide some sample code which illustrates how you'd like this feature to look/work? Thanks!

**Comment by slavap** [comment]
@felangel Sure, something like this:
```dart
class A with EquatableMixin {
  num a;
  num b;
  // rest of fields

  @override
  List<Object> get props => [a, b];
}

var a1 = A(3, 4);
var a2 = A();
a1.copyTo(a2);
```

**Comment by felangel** [comment]
@slavap Sorry but I'm still not sure I understand. Can you try to provide a real-world use case as an example?

**Comment by slavap** [comment]
@felangel 
Real world example: in my class I have many key fields (let's say > 10). In some place I know for sure which ones of them are changed (let's say only two). I want to create new instance with new key fields, so first I create copy of old instance:
```dart
var newObj = MyClass();
oldObj.copyPropsTo(newObj);
newObj.d = newD;
newObj.e = newE;
```
Otherwise I need to copy 10+ fields, or use some third party solution which implements copy method, or user json serialization oldObj.toJson() and newObj.fromJson()

**Comment by wagner1343** [comment]
I guess that what you want:
```
var car = Car("brand", "model");
var carCopy = car.copy()..model = "otherModel";
```
But it not possible to create a generic base method for copy with current props implementation. The reason is because props is just an array of objects, and there is no way to tell wich object goes to wich field when copying.
Maybe this can be solved overriding a method for creating instances from props:
```
abstract class Copiable<T> extends Equatable {
    T fromProps(List props);
    T copy(O other){
        return fromProps(other.props);
    }
}
```
But it looks weird anyway

**Comment by slavap** [comment]
No, if additional method needs to be overridden, then it makes no sense. I would rather use Json serialization methods generator for getting copy functionality implemented.

**Comment by felangel** [comment]
I'm going to close this because I don't think `copyWith` is possible without code generation or additional information. If you want `copyWith` I would recommend using [freezed](https://pub.dev/packages/freezed) or some other generators.
