### ISSUE TITLE
Make stringify = true by default

### ISSUE THREAD

**Issue by rtviwe** [felangel/equatable#60]
I have to always write:
```
@override
bool get stringify => true;
```
Mostly all classes which extends Equatable needs to override toString().

**Comment by felangel** [comment]
Will try to work on a solution which aligns with https://github.com/felangel/equatable/pull/65#issuecomment-634394735.

**Comment by felangel** [comment]
opened a proposal for this in #68. closing this so we can consolidate all thoughts/feedback in #68.
