### ISSUE TITLE
hashcodes different on web vs. flutter app

### ISSUE THREAD

**Issue by sgehrman** [felangel/equatable#63]
I have an Equatable object, I'm creating the same object in the flutter app, then passing the data to a dart web app and noticed the hashCodes are different on the two platforms. I wanted the Ids to match across web and flutter so I could pass the hashcode back and forth to identify the data I wanted, but the hashcodes are different on web and flutter.

**Comment by felangel** [comment]
Hi @sgehrman 👋 
Thanks for opening an issue!

Unfortunately, I don't think there's much that can be done about that. The `Equatable` hashCode is computed from the hashCodes of the individual properties and if those differ across platforms, then the computed hashCode will also be different. I would not rely on hashCodes to be consistent across platforms and use an `id` that you are in control of.

Hope that helps 👍
