### ISSUE TITLE
Nested object equality doesn't work

### ISSUE THREAD

**Issue by techadroit** [felangel/equatable#72]
HI @felangel ,

I have used the following class heirarchy to maintain state. And it works fine with bloc, when trying to test the equality in unit test i get the error. Couldn't figure out what is the issue. 

abstract class Resource{

}

class Uninitialized extends Resource{
  static final Uninitialized _uninitialized = Uninitialized.init();
  factory Uninitialized() => _uninitialized;
  Uninitialized.init();

}

abstract class AppState implements Equatable {

  const AppState();

  @override
  bool get stringify => true;
}

class LoginState extends AppState {
  Resource resource;

  LoginState(this.resource);

  @override
  List<Object> get props => [resource];
}

void main(){
  var demo1 = LoginState(Uninitialized());
  var demo2 = LoginState(Uninitialized());

  test('check for equality',(){
//    assert(demo1 == demo2);
    expect(demo1,equals(demo2));
  });

}

This is the error I am getting on testing

package:test_api                                   expect
package:flutter_test/src/widget_tester.dart 348:3  expect
test\test_sample.dart 27:5                         main.<fn>

Expected: <Instance of 'LoginState'>
  Actual: <Instance of 'LoginState'>

**Comment by felangel** [comment]
Hi @techadroit 👋
Thanks for opening an issue!

I’m guessing your Resource class doesn’t extend equatable or doesn’t have the props override configured properly. Can you please share your Resource class implementation? Thanks 👍

**Comment by techadroit** [comment]
Thanks @felangel for the help, it worked. 👍
