### ISSUE TITLE
Why "equatable" not able for non immutable class?

### ISSUE THREAD

**Issue by devonsunday** [felangel/equatable#75]
**Describe the bug**
I want apply equatable for class with not final fields, but equatable is immutable.

**Comment by Renesanse** [comment]
You can use equatable with mutable classes. @felangel does not recommend it, but you can mixin your mutable class with equatable: 
```dart
// ignore: must_be_immutable
class YourMutableClass with EquatableMixin{}
```
Also, @felangel can you explain please, why you don't want people use equatable with mutable classes?

**Comment by felangel** [comment]
Hi @devonsunday 👋 
Thanks for opening an issue!

The reason for this is:

> AVOID defining custom equality for mutable classes.
> Linter rule: avoid_equals_and_hash_code_on_mutable_classes
> 
> When you define ==, you also have to define hashCode. Both of those should take into account the object’s fields. If those fields change then that implies the object’s hash code can change.
> 
> Most hash-based collections don’t anticipate that—they assume an object’s hash code will be the same forever and may behave unpredictably if that isn’t true.

([source](https://dart.dev/guides/language/effective-dart/design#avoid-defining-custom-equality-for-mutable-classes))

It is also mentioned in the `README.md`

> We can now compare instances of Person just like before without the pain of having to write all of that boilerplate. Note: Equatable is designed to only work with immutable objects so all member variables must be final (This is not just a feature of Equatable - overriding a hashCode with a mutable value can break hash-based collections).

Hope that helps 👍
