### ISSUE TITLE
Lists even if elements are Equatable don't cause changes

### ISSUE THREAD

**Issue by JohnGalt1717** [felangel/equatable#85]
**Describe the bug**
If a list is one of the properties on an object, then add/remove and per item comparisons fail which causes things like FlutterBloc etc. that rely on equitable to determine if something has changed, to also fail.

**To Reproduce**

1. Create an object, add a List<equatable> property and add it to props
2. Add an item to the list, note that nothing changes and equatable still doesn't equal and as a result FlutterBloc etc. won't update.
3. Remove an item from the list. Note that nothing changes in the status of equatable.

**Expected behavior**
Equatable should by default inspect all elements for equatableness of a list and flag the property dirty based on an mismatch in size or specific elements changing. Alternatively this should be a setting that you can configure, or there should be a specific type of list (EquatableList<>) that will explicitly cause the same.

**Version**
Dart SDK version: 2.10.0-7.3.beta (beta) (Wed Aug 26 09:46:50 2020 +0200) on "windows_x64"

**Comment by felangel** [comment]
Hi @JohnGalt1717 👋 
Thanks for opening an issue!

Can you please provide a link to a reproduction sample? Thanks! 🙏

**Comment by JohnGalt1717** [comment]
@felangel Don't know what there is to reproduce. Lists don't cause equatable to change status. It's that simple.  It ignores add/deletes of items from the list.

**Comment by felangel** [comment]
@JohnGalt1717 having a concrete reproduction sample would help because we can be sure we are looking at the exact same scenario.

For example, are you mutating the list (sounds like it) or are you creating a new instance of the list with the added item? I'm happy to take the time to investigate this but I would really appreciate if you could take the time to create a simple reproduction sample, thanks!

**Comment by JohnGalt1717** [comment]
Standard process of immutable classses.

Create one with a list.
Create a copy and update the list
compare the original class with the updated class. Still shows that it's equal even though the lists are different.

**Comment by felangel** [comment]
There are currently tests for this https://github.com/felangel/equatable/blob/baf9a669d97fd68b41cdb1a3c4afcac72c6d0dfe/test/equatable_test.dart#L655. Is there a case that is missing? I'm not sure why you are so resistant to sharing a small chunk of code which reproduces the issue you're facing. It's making it harder to reach a solution.

**Comment by JohnGalt1717** [comment]
I'm trying to.

create a class, put a property in the class that is a list, set props = [listprop]
Create an instance of said class with something in the list.
Create a copy of said class
Add another item the list of the copy

Compare the original and the copy of the class.

Equatable says that the 2 are the same. They are not.

The tests you just linked to compare 2 lists, not to objects with lists in them.

**Comment by felangel** [comment]
Rather than describing in words can you share the dart code? There are tests for classes with lists in them as well:
https://github.com/felangel/equatable/blob/baf9a669d97fd68b41cdb1a3c4afcac72c6d0dfe/test/equatable_test.dart#L497

**Comment by JohnGalt1717** [comment]
The following:

```
import 'package:equatable/equatable.dart';

class ListObject extends Equatable {
  final bool isValue;
  ListObject(this.isValue);

  @override
  // TODO: implement props
  List<Object> get props => [isValue];
}

class A extends Equatable {
  final List<ListObject> values;
  final String someString;

  A(this.values, this.someString);

  @override
  // TODO: implement props
  List<Object> get props => [values, someString];
}

void main() {
  final objA = new A(List<ListObject>(), "something");

  final objB = new A(objA.values, objA.someString);
  objB.values.add(ListObject(true));

  print(objA == objB); //Should be false

  final objC = new A(objB.values, objB.someString);
  objC.values.add(ListObject(true));

  print(objB == objC); //Should be false
}
```

Results in equatable = true on line 29 and 34.

They're clearly not because objB doesn't have the same number of elements that objC has in values as an example.

It should have returned false in both cases because values has a different length.

**Comment by felangel** [comment]
@JohnGalt1717 this is because you are mutating values. If instead you created a new instance of objB with a `copyWith` then things would work as expected:

```dart
final objC = objB.copyWith(values: List.of(objB.values)..add(ListObject(true)));
print(objA == objB); // will be false
```

Hope that helps 👍
