### ISSUE TITLE
Mark a props equals if is identical

### ISSUE THREAD

**Issue by sm2017** [felangel/equatable#91]
@felangel Is it possible to mark an specific `prop` that is equal when it's identical?

```dart
import 'package:equatable/equatable.dart';

class Person extends Equatable {
  final String name;
  final List<int> orders;

  Person(this.name,this.orders);

  @override
  List<Object> get props => [name,orders];
}
```

I need a way to told dart that two person in equal if has same name but has `identical` orders not **deep equal** orders

I think we can achieve by following way

```dart
import 'package:equatable/equatable.dart';

class Person extends Equatable {
  final String name;
  final List<int> orders;

  Person(this.name,this.orders);

  @override
  List<Object> get props => [name];

  @override
  List<Object> get identicalProps => [orders];
}
```

**Comment by felangel** [comment]
Hi @sm2017 👋
Thanks for opening an issue!

Can you provide a bit more context regarding why you have this requirement and what you are trying to achieve? Thanks! 🙏

**Comment by sm2017** [comment]
I want to add `RefreshIndicator` in my listview and in my bloc I do the same as https://github.com/felangel/bloc/blob/90cebad4c039080c98f8daf3adc6e6a5f189a315/docs/_snippets/flutter_weather_tutorial/refresh_indicator.dart.md

I want to keep the latest data while pull to refresh finished its job , so I don't emit `Loading` state once I refresh, when I get fresh data from server, as two `orders` is deep equal, the future of RefreshIndicator never completed

So I need a way to fix it

**Comment by felangel** [comment]
You can add a lastUpdated property to the state so you know when it was late updated. Another option is to use cubit check out the latest refresh implementation in the flutter weather example. Let me know if that helps 👍

**Comment by sm2017** [comment]
What about `hashCode` is it okay? 

```
class Person extends Equatable {
  final String name;
  final List<int> orders;

  Person(this.name,this.orders);

  @override
  List<Object> get props => [name];

  @override
  List<Object> get identicalProps => [ordersHashCode];

  get int ordersHashCode => orders.hashCode
}

```

**Comment by sm2017** [comment]
What about hashCode is it okay?

```dart
class Person extends Equatable {
  final String name;
  final List<int> orders;

  Person(this.name,this.orders);

  @override
  List<Object> get props => [name,ordersHashCode];

  get int ordersHashCode => orders.hashCode
}
```

**Comment by felangel** [comment]
I don’t think hashCode is required to be different for different instances so it’s not a safe assumption.

**Comment by sm2017** [comment]
@felangel I'm newbie in dart, Can you show me an example that demonstrate `hashCode` is not safe for this use case , Or can you refer me to a doc?

**Comment by sm2017** [comment]
>A hash code is a single integer which represents the state of the object that affects operator == comparisons.

> All objects have hash codes. The default hash code represents only the identity of the object, the same way as the default operator == implementation only considers objects equal if they are identical (see identityHashCode).

**Comment by felangel** [comment]
> Objects that are not equal are allowed to have the same hash code, it is even technically allowed that all instances have the same hash code, but if clashes happen too often, it may reduce the efficiency of hash-based data structures like HashSet or HashMap.

https://api.dart.dev/stable/2.10.3/dart-core/Object/hashCode.html

**Comment by sm2017** [comment]
Ok, please read again my last response
What you think about this line?

https://github.com/felangel/equatable/blob/master/lib/src/equatable_utils.dart#L24

**Comment by felangel** [comment]
yes but it can be overridden so it's not a safe assumption in every case. It might work for your case but I don't think it's a good general rule.

**Comment by sm2017** [comment]
Thanks a lot, I understand, Currently I'm talking about comparing `List`s
