### ISSUE TITLE
Support different props for == and hashcode

### ISSUE THREAD

**Issue by nguyenxndaidev** [felangel/equatable#96]
# Problem
I have a class, which contains fields: `id` and `name`.
I want to calculate hashcode from only field `id`, but `==` should be calculated from both fields.

# Workaround
My workaround for now is to manually implement hashcode function and use `props` for `==`.

**Comment by felangel** [comment]
Hi @nguyenxndaidev 👋 
Thanks for opening an issue!

Can you please provide more context around the use-case that you have? Thanks!

**Comment by nguyenxndaidev** [comment]
I think there are 2 rules when working with hashcode and equals:
* If equals returns true, then hashcode must return the same value.
* If the hashcode of two objects are the same, then the two objects don’t have to be equal but they can be equal.

With current implementation, we are forcing "if hashcode of two objects are the same, they must be equal".
Usually, when working with objects in database, we know that we only need the id for hashcode, and equal will contains id and additional business fields.

**Comment by RandalSchwartz** [comment]
I'm with @felangel ... what's the use case for this?  Why not mix together as many bits to make it distinct as you can?  I guess coding in 1981 in Smalltalk has spoiled me a bit. 👍

**Comment by nguyenxndaidev** [comment]
Never mind 😄, I just found that I can save time for the hashcode computation but it's not so important in most cases. I can overwrite the hashcode method with the IDE anytime if I want to.
