### ISSUE TITLE
Add a displayableProps

### ISSUE THREAD

**Issue by LefebvreIlyas** [felangel/equatable#99]
Hello @felangel,
Thank you very much for your work on all the packages. 🎆

Sometimes you need to compare objects on certain fields, but to display others using the `toString`.

```dart
abstract class Equatable {
  List<Object> get props;

  List<Object> get displayableProps => props;
}
```

**Display all the props.**
This is the default behavior.

```dart
class Foo extends Equatable {
  // Fields

  @override
  List<Object> get props => <Object>[
      foo,
      bar,
      baz,
      foobar,
  ];
}
```

**Display and compare different fields.**

```dart
class Foo extends Equatable {
  // Fields

  @override
  List<Object> get props => <Object>[
      foo,
      bar,
  ];

  @override
  List<Object> get displayableProps => <Object>[
      baz,
      foobar,
  ];
}
```

**Display all properties except one**

```dart
class Foo extends Equatable {
  // Fields

  @override
  List<Object> get props => <Object>[
      foo,
      bar,
      baz,
      foobar,
  ];

  @override
  List<Object> get displayableProps => props.removeAt(0);
}
```

**Comment by felangel** [comment]
Hi @LefebvreIlyas 👋 
Thanks for opening an issue!

If you would like custom `toString` behavior, I would recommend just overriding `toString` manually for the one-off cases. 

```dart
class Foo extends Equatable {
  // Fields

  @override
  List<Object> get props => <Object>[
      foo,
      bar,
      baz,
      foobar,
  ];

  @override
  String toString() => 'Foo($bar, $baz, $foobar)`;
}
```

Hope that helps! Closing for now but feel free to comment with additional comments/questions and I'm happy to continue the conversation 👍
